# Generated by Django 3.2.19 on 2023-08-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
